services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d warehouse"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - etl-networks

  etl:
    build: .
    environment:
      DB_URL: ${DB_URL:-postgresql://postgres:postgres@db:5432/warehouse}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - etl-networks

volumes:
  db_data:

networks:
  etl-networks:
    driver: bridge